adding required files for f35-py310 S2I image to built

diff --git a/f35-py310/s2i_assemble.patch b/f35-py310/s2i_assemble.patch
--- a/f35-py310/s2i_assemble.patch
+++ b/f35-py310/s2i_assemble.patch
@@ -1,7 +1,7 @@
---- a/assemble    2021-12-07 00:00:27.196199956 -0500
-+++ b/assemble    2021-12-07 00:00:32.284209605 -0500
+--- a/assemble    2022-03-10 08:11:46.618770837 -0800
++++ b/assemble    2022-03-10 08:20:27.559837644 -0800
 @@ -14,38 +14,8 @@
-     python3.8 -m venv $1
+     python3.10 -m venv $1
  }
 
 -# Install pipenv or micropipenv to the separate virtualenv to isolate it
@@ -39,7 +39,15 @@
  shopt -s dotglob
  echo "---> Installing application source ..."
  mv /tmp/src/* "$HOME"
-@@ -62,28 +32,7 @@
+@@ -56,38 +26,17 @@
+
+ if [[ ! -z "$UPGRADE_PIP_TO_LATEST" ]]; then
+   echo "---> Upgrading pip, setuptools and wheel to latest version ..."
+-  if ! pip install -U pip setuptools wheel; then
++  if ! pip install --no-cache-dir --disable-pip-version-check -U pip setuptools wheel; then
+     echo "WARNING: Installation of the latest pip, setuptools and wheel failed, trying again from official PyPI with pip --isolated install"
+-    pip install --isolated -U pip setuptools wheel
++    pip install --no-cache-dir --disable-pip-version-check --isolated -U pip setuptools wheel
    fi
  fi
 
@@ -67,5 +75,10 @@
 -fi
 +thamos install
 
- if [[ -f setup.py && -z "$DISABLE_SETUP_PY_PROCESSING" ]]; then
+ if [[ ( -f setup.py || -f setup.cfg ) && -z "$DISABLE_SETUP_PY_PROCESSING" ]]; then
    echo "---> Installing application ..."
+-  pip install .
++  pip install --no-cache-dir --disable-pip-version-check .
+ fi
+
+ if should_collectstatic; then
